import Head from "next/head";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { api } from "~/utils/api";

const CreatePostWizard = () => {
  const { user } = useUser();
  if (!user) return null;
  console.log(user);
  return (
    <div className="flex w-full gap-4">
      <img
        src={user.imageUrl}
        alt="Profile image"
        className="h-16 w-16 rounded-full"
      />
      <input
        placeholder="Type some emojis!"
        className="grow rounded-md bg-transparent p-2 text-white outline-none"
      />
      {/* <SignOutButton>
        <div className="rounded-md bg-violet-600 p-2 text-white">Sign Out</div>
      </SignOutButton> */}
    </div>
  );
};

export default function Home() {
  const user = useUser();
  const { data, isLoading } = api.posts.getAll.useQuery();
  if (isLoading) return <p>Loading...</p>;
  if (!data) return <p>No posts found</p>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-500 md:max-w-2xl">
          <div className="flex border-b border-slate-500 p-4">
            {!user.isSignedIn && <SignInButton />}
            {!!user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className="w-full">
            {data?.map(({ post, author }) => (
              <div
                key={post.id}
                className="flex gap-4 border-b-2 border-slate-500 p-6"
              >
                <div className="text-white">{post.content}</div>
                <div className="text-slate-500">{author?.username}</div>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
